server:
  port: 8080
  servlet:
    context-path: /api    #应用的上下文路径，详细参考 云枢帮助中心-开发者手册-解决跨域安全问题
  domain: http://127.0.0.1:8080

spring:
  #数据源
  datasource:
    #数据库驱动:
    #driver-class-name: oracle.jdbc.OracleDriver # Oracle
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver # SQL Server
    #driver-class-name: com.mysql.cj.jdbc.Driver # DM
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL
    #数据库连接：
    #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl                                                                                     # Oracle
    #url: jdbc:sqlserver://127.0.0.1:3433;database=cloudpivot                                                                       # SQL Server
    #url: url: jdbc:dm://127.0.0.1:5236/cloudpivot                                                                                  # DM
    #    url: jdbc:mysql://127.0.0.1:3306/cloudpivot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false # MySQL
    #    url: jdbc:mysql://172.18.14.204:3306/cloudpivot-206?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false # MySQL
    #    url: jdbc:mysql://172.31.13.109:3306/mysql-610?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false # MySQL
    url: jdbc:mysql://172.31.13.109:3306/test-6.9?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false # MySQL
    #    url: jdbc:mysql://rm-wz98a39kb07da4ch2.mysql.rds.aliyuncs.com:3306/h3bpm_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false # MySQL
    username: root
    password: testyun123456
    #    password: test123456!@#$%
    hikari:
      maximum-pool-size: 10                                     # 连接池最大连接数. 根据系统并发用户数设置合理值
      minimum-idle: 1                                           # 连接池最小空闲连接数量
      #connection-test-query: select 1                           # 测试连接是否可用的查询语句 (MySQL, SQLServer)
      #connection-test-query: select 1 from dual                # 测试连接是否可用的查询语句 (Oracle)

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #database-platform: org.hibernate.dialect.Oracle12cDialect       # Oracle
    #database-platform: org.hibernate.dialect.SQLServerDialect       # SQL Server
    #database-platform: org.hibernate.dialect.DmDialect              # DM
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect     # MySQL
    show-sql: true
  redis:
    host: 172.31.13.109  #地址
    database: 10         #
    port: 6379          #端口
    prefix: ""
    password: H3yuncom
  quartz:
    auto-startup: false  #本地启动时，不加入quartz集群

logging:
  level:
    com.authine.cloudpivot: debug   # 云枢产品日志输出级别
    com.authine.cloudpivot.web.sso: debug
    com.authine.cloudpivot.foundation.orm.impl.dml: trace # 表单操作SQL打印
    com.authine.cloudpivot.ext.controller: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


cloudpivot:
  is_edas: true
  bizobject:
    bizmethod-invoke-timeout-seconds: 10      #业务集成默认超时时间，单位：秒
    db:
      type: mysql                             #数据库类型名称，支持mysql, oracle, sqlserver, dm
  swagger:
    enabled: true           #开启Swagger API. API 访问地址: http://hostname:port/context-path/doc.html 或者 http://hostname:port/context-path/swagger-ui.html
    defaultRuleApiOn: false   #为true时 swagger显示默认业务规则API
  report:
    datasourceurl: http://127.0.0.1
  license:
    licenseFile: cloudpivot.license #许可证文件
  login:
    dingtalk: false #钉钉方式登录
    accountpassword: true #账号密码登录
    dingtalk&accountpassword: true #钉钉扫码和账号密码方式登录
  attachment: # 文件存储方式
    oss:
      enabled: false     #是否启用
    sftp:
      enabled: true     #是否启用
  api:
    oauth:
      enabled: true   # 是否开启权限校验
      test:
        userid: afeb204e71a9d3050171a9d464e60001      # 模拟测试用户ID，不能用于生产环境
  webmvc:
    corsmappings: true           #配置是否允许跨域，详细参考 云枢帮助中心-开发者手册-解决跨域安全问题
    corsAllowedOrigins: '*'      #跨域请求白名单,多个地址以逗号分割
  dingtalk:
    client:
      dingtalk_server_proxy: http://172.18.14.204/
    is_syn_edu: true               #是否同步家校通讯录
  wechat:
    client:
      aes_key: IjsfohGaWd5nncXxUzOaF7PY8rYoufbf3zgOjd1B0IZ
      aes_token: LI1uHiaQvGer
    proxy:
      default_cp_base_url: http://172.18.14.201/wx_base_url        #微信基数接口数据代理
      scan_qrconnect: http://172.18.14.201/wx_scan         #微信扫码登录代理

  task:
    enabled: false                            #是否开启定时任务，在集群部署环境下只开启一个节点的定时任务
  workItem:
    participant_number: 1000                  #待办 传阅 加签 等参与者数量限制
  message:
    profile:
      active: simple                          #消息类型，simple：进程内消息，kafka：kafka中间件，默认simple
  event_push:
    enable: false                             #是否开启事件订阅推送
  orgSync: # 组织增量同步
    enable: true # 是否开启
    retryCount: 3 # 钉钉回调事件处理失败重试次数
    consumeCron: 0/10 * * * * ? # 消息同步日志cron表达式
    defaultPassword: 12345678       #默认创建用户的初始密码，必须大于6位数的长度

caffeine:
  region:
    default: 1000, 12h #默认内存缓存配置 单个region, 最大持有1000个缓存key, 写后12小时过期
  # 启用二级缓存
  l2-cache-open: true