alter table H_RELATED_CORP_SETTING add ENABLED NUMBER;

comment on column H_RELATED_CORP_SETTING.ENABLED is '是否禁用';

alter table H_ORG_USER add ENABLED NUMBER;

comment on column H_ORG_USER.ENABLED is '是否禁用';

alter table H_ORG_DEPARTMENT add ENABLED NUMBER;

comment on column H_ORG_DEPARTMENT.ENABLED is '是否禁用';

UPDATE H_RELATED_CORP_SETTING SET ENABLED = 1 WHERE ID != '';
UPDATE H_ORG_USER SET ENABLED = 1 WHERE ID != '';
UPDATE H_ORG_DEPARTMENT SET ENABLED = 1 WHERE ID != '';