create table H_WORKFLOW_ADMIN
(
  ID           VARCHAR2(120) not null,
  CREATER      VARCHAR2(120),
  CREATEDTIME  DATE,
  DELETED      NUMBER(1),
  MODIFIER     VARCHAR2(120),
  MODIFIEDTIME DATE,
  REMARKS      VARCHAR2(200),
  ADMINTYPE    VARCHAR2(120),
  WORKFLOWCODE VARCHAR2(200),
  MANAGESCOPE  VARCHAR2(512),
  OPTIONS      CLOB
);
create index IDX_WORKFLOW_ADMIN_CODE on H_WORKFLOW_ADMIN (WORKFLOWCODE);