create table H_WORKFLOW_ADMIN_SCOPE
(
  ID           VARCHAR2(120) not null,
  CREATER      VARCHAR2(120),
  CREATEDTIME  DATE,
  DELETED      NUMBER(1),
  MODIFIER     VARCHAR2(120),
  MODIFIEDTIME DATE,
  REMARKS      VARCHAR2(200),
  ADMINID      VARCHAR2(120),
  UNITTYPE     VARCHAR2(120),
  UNITID       VARCHAR2(36)
);
create index IDX_WORKFLOW_ADMINID on H_WORKFLOW_ADMIN_SCOPE (ADMINID);
