CREATE TABLE h_related_corp_setting (
  id varchar2(120)  NOT NULL   primary key,
  creater varchar2(120)  DEFAULT NULL,
  createdTime date DEFAULT NULL,
  deleted number(1, 0) DEFAULT NULL,
  modifier varchar2(120)  DEFAULT NULL,
  modifiedTime date DEFAULT NULL,
  remarks varchar2(200)  DEFAULT NULL,
  agentId varchar2(120)  DEFAULT NULL,
  appSecret varchar2(120)  DEFAULT NULL,
  appkey varchar2(120)  DEFAULT NULL,
  corpId varchar2(120)  DEFAULT NULL,
  corpSecret varchar2(120)  DEFAULT NULL,
  exportHost varchar2(36)  DEFAULT NULL,
  extend1 varchar2(120)  DEFAULT NULL,
  extend2 varchar2(120)  DEFAULT NULL,
  extend3 varchar2(120)  DEFAULT NULL,
  extend4 varchar2(120)  DEFAULT NULL,
  extend5 varchar2(120)  DEFAULT NULL,
  headerNum int DEFAULT NULL,
  name varchar2(240)  DEFAULT NULL,
  orgType varchar2(12)  DEFAULT NULL,
  relatedType varchar2(12)  DEFAULT NULL,
  scanAppId varchar2(120)  DEFAULT NULL,
  scanAppSecret varchar2(200)  DEFAULT NULL,
  redirectUri varchar2(200)  DEFAULT NULL,
  synRedirectUri varchar2(120)  DEFAULT NULL,
  pcServerUrl varchar2(120)  DEFAULT NULL,
  mobileServerUrl varchar2(120)  DEFAULT NULL,
  syncType varchar2(12)  DEFAULT NULL
);
