CREATE TABLE `h_biz_remind` (
  `id` varchar(120) COLLATE utf8_bin NOT NULL,
  `creater` varchar(120) COLLATE utf8_bin DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `deleted` bit(1) DEFAULT NULL,
  `modifier` varchar(120) COLLATE utf8_bin DEFAULT NULL,
  `modifiedTime` datetime DEFAULT NULL,
  `remarks` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `conditionType` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `dateOption` varchar(300) COLLATE utf8_bin DEFAULT NULL,
  `dateType` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `depIds` longtext COLLATE utf8_bin,
  `enabled` bit(1) DEFAULT NULL,
  `filterType` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `intervalTime` int(11) DEFAULT NULL,
  `msgTemplate` varchar(500) COLLATE utf8_bin DEFAULT NULL,
  `remindType` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `roleCondition` longtext COLLATE utf8_bin,
  `roleIds` longtext COLLATE utf8_bin,
  `schemaCode` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `sheetCode` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `userDataOptions` longtext COLLATE utf8_bin,
  `userIds` longtext COLLATE utf8_bin,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='表单消息提醒表';