ALTER TABLE `h_business_rule`
MODIFY COLUMN `id` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL FIRST,
MODIFY COLUMN `creater` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `createdTime`,
MODIFY COLUMN `modifier` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `modifiedTime`,
MODIFY COLUMN `bizRuleType` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `schedulerSetting`,
MODIFY COLUMN `code` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `defaultRule`,
MODIFY COLUMN `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `code`,
MODIFY COLUMN `schemaCode` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `name`,
MODIFY COLUMN `remarks` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `schemaCode`;